server:
  port: 8090

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      product-validation-success: product-validation-success
      product-validation-fail: product-validation-fail
    consumer:
      group-id: product-validation-group
      auto-offset-reset: latest

    data:
      mongodb:
        database: admin
        uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017/admin}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:product-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSRWORD:123456}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
      org:
        apache:
          kafka: OFF